add swagger-user
olgaX2a/goit-team-project-kapusta-server pull request #11
Opened 2021-11-12 08:49 UTC by Bithmark

Проблема с верификацией так же осталась. Верификацию через свагер он не подтверждает.

2021-11-12 12:17 UTC, olgaX2a requested changes

2021-11-12 12:17 UTC, olgaX2a commented on chlam.js
> +  },
что это за файл?
если это хлам, то не стоит его отправлять в пул реквесте 😉
можно просто хранить его у себя локально

2021-11-12 12:17 UTC, olgaX2a commented on routes/api/users.js
> +router.post("/logout", authenticate, controllerWrapper(logout));
а почему не применился prettier с одинарными кавычками?

2021-11-12 12:17 UTC, olgaX2a commented on swagger.json
> +  "servers": [{ "url": "http://localhost:3000/api" }],
вот тут, наверно, всё-таки не localhost, а [heroku](http://goit-kapusta.herokuapp.com/api)

2021-11-12 14:15 UTC, Bithmark commented on chlam.js
> +  },
Я просто пытался по разному играться вот он и остался

2021-11-12 14:16 UTC, Bithmark commented on routes/api/users.js
> +router.post("/logout", authenticate, controllerWrapper(logout));
Без понятия

2021-11-12 14:16 UTC, Bithmark commented on swagger.json
> +  "servers": [{ "url": "http://localhost:3000/api" }],
Я у себя изменил уже

2021-11-12 14:24 UTC, olgaX2a commented on swagger.json
> +  "servers": [{ "url": "http://localhost:3000/api" }],
так коммит в студию) в эту же ветку, он подтянется к пул реквесту

2021-11-13 15:23 UTC, olgaX2a requested changes
исправить конфликты в файле routes/api/users.js
удалить файл chlam.js

2021-11-13 15:23 UTC, olgaX2a commented on routes/api/users.js
> +router.patch('/balance', authenticate, controllerWrapper(balanceUpdate));
зачем это 2 раза? см. выше с 11 строки - у тебя те же операции

2021-11-13 15:23 UTC, olgaX2a commented on chlam.js
> +  },
удали его, пожалуйста

2021-11-13 18:59 UTC, olgaX2a approved these changes

2021-11-13 18:59 UTC, merged